version: 0.0
os: windows
files:
  - source: /
    destination: C:\Users\Administrator\Desktop\deploy
hooks:
  BeforeInstall:
    - location: install.bat
      timeout: 300
      runas: administrator
  AfterInstall: 
    - location: serverconnect.bat
      runas: administrator
